<?php

namespace Librinfo\EmailBundle\tests\Functional;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-05-04 at 15:18:32.
 * Modified by Quotidianus
 */
use PHPUnit\Framework\TestCase;
use Librinfo\EmailBundle\Entity\Email;
use Librinfo\EmailBundle\Entity\EmailLink;

class EmailTest extends TestCase {

    /**
     * @var Email
     */
    protected $emailtest;
    protected $emaillinkmock;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->emailtest = new Email;
        $this->emaillinkmock = $this->createMock('Librinfo\EmailBundle\Entity\EmailLink');
        $this->emailreceiptmock = $this->createMock('Librinfo\EmailBundle\Entity\EmailReceipt');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::initCollections
     * @todo   Implement testInitCollections().
     */
    public function testInitCollections() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::__clone
     * @todo   Implement test__clone().
     */
    public function test__clone() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setFieldFrom
     */
    public function testSetFieldFrom() {
        $this->emailtest->setFieldFrom('you@me.us');
        $this->assertEquals('you@me.us', $this->emailtest->getFieldFrom());
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getFieldFrom
     */
    public function testGetFieldFrom() {
        $from = $this->emailtest->getFieldFrom();
        $this->assertEquals($from, '');
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setFieldTo
     */
    public function testSetFieldTo() {
        $this->emailtest->setFieldTo('me@you.us');
        $this->assertEquals('me@you.us', $this->emailtest->getFieldTo());
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getFieldTo
     */
    public function testGetFieldTo() {
        $to = $this->emailtest->getFieldTo();
        $this->assertEquals($to, '');
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setFieldCc
     */
    public function testSetFieldCc() {
        $this->emailtest->setFieldCc('me@he.us');
        $this->assertEquals('me@he.us', $this->emailtest->getFieldCc());
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getFieldCc
     */
    public function testGetFieldCc() {
        $tocc = $this->emailtest->getFieldCc();
        $this->assertEquals($tocc, '');
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setFieldBcc
     */
    public function testSetFieldBcc() {
        $this->emailtest->setFieldBcc('me@they.us');
        $this->assertEquals('me@they.us', $this->emailtest->getFieldBcc());
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getFieldBcc
     */
    public function testGetFieldBcc() {
        $tobcc = $this->emailtest->getFieldBcc();
        $this->assertEquals($tobcc, '');
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setFieldSubject
     */
    public function testSetFieldSubject() {
        $this->emailtest->setFieldSubject('Email subject');
        $this->assertEquals('Email subject', $this->emailtest->getFieldSubject());
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getFieldSubject
     */
    public function testGetFieldSubject() {
        $subject = $this->emailtest->getFieldSubject();
        $this->assertEquals($subject, '<no subject>');
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setContent
     */
    public function testSetContent() {
        $this->emailtest->setContent('Email html content');
        $this->assertEquals('Email html content', $this->emailtest->getContent());
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getContent
     */
    public function testGetContent() {
        $content = $this->emailtest->getContent();
        $this->assertEquals($content, '');
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setTextContent
     */
    public function testSetTextContent() {
        $this->emailtest->setTextContent('Email text content');
        $this->assertEquals('Email text content', $this->emailtest->getTextContent());
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getTextContent
     */
    public function testGetTextContent() {
        $textcontent = $this->emailtest->getTextContent();
        $this->assertEquals($textcontent,"");
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setSent
     */
    public function testSetSent() {
        $this->emailtest->setSent(true);
        $this->assertTrue($this->emailtest->getSent());
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getSent
     */
    public function testGetSent() {
        $sent = $this->emailtest->getSent();
        $this->assertFalse($sent);
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::addAttachment
     * @todo   Implement testAddAttachment().
     */
    public function testAddAttachment() {
        $this->markTestIncomplete(
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::addLibrinfoFile
     * @todo   Implement testAddLibrinfoFile().
     */
    public function testAddLibrinfoFile() {
        $this->markTestIncomplete(
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::removeAttachment
     * @todo   Implement testRemoveAttachment().
     */
    public function testRemoveAttachment() {
        $this->markTestIncomplete(
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::removeLibrinfoFile
     * @todo   Implement testRemoveLibrinfoFile().
     */
    public function testRemoveLibrinfoFile() {
        $this->markTestIncomplete(
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getAttachments
     * @todo   Implement testGetAttachments().
     */
    public function testGetAttachments() {
        $this->markTestIncomplete(
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getLibrinfoFiles
     * @todo   Implement testGetLibrinfoFiles().
     */
    public function testGetLibrinfoFiles() {
        $this->markTestIncomplete(
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setAttachments
     * @todo   Implement testSetAttachments().
     */
    public function testSetAttachments() {
        $this->markTestIncomplete(
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setIsTest
     */
    public function testSetIsTest() {
        $this->emailtest->setIsTest(true);
        $this->assertTrue($this->emailtest->getIsTest());
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getIsTest
     */
    public function testGetIsTest() {
        $istest = $this->emailtest->getIsTest();
        $this->assertFalse($istest);
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getTestAddress
     */
    public function testGetTestAddress() {
        $testaddress = $this->emailtest->getTestAddress();
        $this->assertEquals($testaddress,"");
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setTestAddress
     */
    public function testSetTestAddress() {
        $this->emailtest->setTestAddress('Email address test');
        $this->assertEquals('Email address test', $this->emailtest->getTestAddress());
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getTemplate
     */
    public function testGetTemplate() {
        $template = $this->emailtest->getTemplate();
        $this->assertEquals($template,"");
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setTemplate
     */
    public function testSetTemplate() {
        $this->emailtest->setTemplate('Email template');
        $this->assertEquals('Email template', $this->emailtest->getTemplate());
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setIsTemplate
     */
    public function testSetIsTemplate() {
        $this->emailtest->setIsTemplate(true);
        $this->assertTrue($this->emailtest->getIsTemplate());
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getIsTemplate
     */
    public function testGetIsTemplate() {
        $istemplate = $this->emailtest->getIsTemplate();
        $this->assertFalse($istemplate);
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getNewTemplateName
     */
    public function testGetNewTemplateName() {
        $newtemplatename = $this->emailtest->getNewTemplateName();
        $this->assertEquals($newtemplatename, '');
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setNewTemplateName
     */
    public function testSetNewTemplateName() {
        $this->emailtest->setNewTemplateName('New template name');
        $this->assertEquals('New template name', $this->emailtest->getNewTemplateName());
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setTracking
     */
    public function testSetTracking() {
        $this->emailtest->setTracking(true);
        $this->assertTrue($this->emailtest->getTracking());
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getTracking
     */
    public function testGetTracking() {
        $tracking = $this->emailtest->getTracking();
        $this->assertFalse($tracking);
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::addReceipt
     * @covers Librinfo\EmailBundle\Entity\Email::removeReceipt
     * @covers Librinfo\EmailBundle\Entity\Email::getReceipts
     */
    public function testAddReceiptRemoveReceiptGetReceipts() {
        $this->emailtest->addReceipt($this->emailreceiptmock);
        $this->assertArraySubset(array($this->emailreceiptmock), $this->emailtest->getReceipts());
        $this->emailtest->removeReceipt($this->emailreceiptmock);
        $this->assertNotContains(array($this->emailreceiptmock), $this->emailtest->getReceipts());
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::addLink
     * @covers Librinfo\EmailBundle\Entity\Email::removeLink
     * @covers Librinfo\EmailBundle\Entity\Email::getLinks
     */
    public function testAddLinkRemoveLinkGetLinks() {
        $this->emailtest->addLink($this->emaillinkmock);
        $this->assertArraySubset(array($this->emaillinkmock), $this->emailtest->getLinks());
        $this->emailtest->removeLink($this->emaillinkmock);
        $this->assertNotContains(array($this->emaillinkmock), $this->emailtest->getLinks());
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getId
     * @todo   Implement testGetId().
     */
    public function testGetId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setId
     * @todo   Implement testSetId().
     */
    public function testSetId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::isNew
     * @todo   Implement testIsNew().
     */
    public function testIsNew() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::addSearchIndex
     * @todo   Implement testAddSearchIndex().
     */
    public function testAddSearchIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::removeSearchIndex
     * @todo   Implement testRemoveSearchIndex().
     */
    public function testRemoveSearchIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getSearchIndexes
     * @todo   Implement testGetSearchIndexes().
     */
    public function testGetSearchIndexes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setSearchIndexes
     * @todo   Implement testSetSearchIndexes().
     */
    public function testSetSearchIndexes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::analyseField
     * @todo   Implement testAnalyseField().
     */
    public function testAnalyseField() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getCreatedAt
     */
    public function testGetCreatedAt() {
        $date = $this->emailtest->getCreatedAt();
        $this->assertEquals($date, '');
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setCreatedAt
     */
    public function testSetCreatedAt() {
        $date = new \DateTime("now");
        $this->emailtest->setCreatedAt($date);
        $this->assertEquals($date, $this->emailtest->getCreatedAt());
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getUpdatedAt
     */
    public function testGetUpdatedAt() {
        $date = $this->emailtest->getUpdatedAt();
        $this->assertEquals($date, '');
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setUpdatedAt
     */
    public function testSetUpdatedAt() {
        $date = new \DateTime("now");
        $this->emailtest->setUpdatedAt($date);
        $this->assertEquals($date, $this->emailtest->getUpdatedAt());
    }

}
